Regele Marius/Models/Specializare.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Regele_Marius.Models
{
    public class Specializare
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Specializare")]
        public string Nume { get; set; }

    }
}

Regele Marius/Controllers/SpecializaresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Regele_Marius.Models;

namespace Regele_Marius.Controllers
{
    public class SpecializaresController : Controller
    {
        private ContextClinica db = new ContextClinica();

        // GET: Specializares
        public ActionResult Index()
        {
            return View(db.Specializari.ToList());
        }

        // GET: Specializares/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Specializare specializare = db.Specializari.Find(id);
            if (specializare == null)
            {
                return HttpNotFound();
            }
            return View(specializare);
        }

        // GET: Specializares/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Specializares/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nume")] Specializare specializare)
        {
            if (ModelState.IsValid)
            {
                if (db.Specializari.Any(x => x.Nume == specializare.Nume))
                    ModelState.AddModelError("Nume", "Specializare existenta");
                else
                {
                    db.Specializari.Add(specializare);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(specializare);
        }

        // GET: Specializares/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Specializare specializare = db.Specializari.Find(id);
            if (specializare == null)
            {
                return HttpNotFound();
            }
            return View(specializare);
        }

        // POST: Specializares/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nume")] Specializare specializare)
        {
            if (ModelState.IsValid)
            {
                db.Entry(specializare).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(specializare);
        }

        // GET: Specializares/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Specializare specializare = db.Specializari.Find(id);
            if (specializare == null)
            {
                return HttpNotFound();
            }
            return View(specializare);
        }

        // POST: Specializares/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Specializare specializare = db.Specializari.Find(id);
            db.Specializari.Remove(specializare);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Regele Marius/Views/Specializares/Create.cshtml
@model Regele_Marius.Models.Specializare

@{
    ViewBag.Title = "Adaugare specializare";
    if (Session["NumeUtilizator"] == null || (bool)Session["Activ"] == true)
    {
        Response.Redirect("~/Cont/Logare", false);
    }
}

<h2>Adaugare specializare</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nume, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nume, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nume, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

Regele Marius/Views/Specializares/Delete.cshtml
@model Regele_Marius.Models.Specializare

@{
    ViewBag.Title = "Delete";
    if (Session["NumeUtilizator"] == null || (bool)Session["Activ"] == true)
    {
        Response.Redirect("~/Cont/Logare", false);
    }
}

<h2>Sigur vrei sa stergi aceasta specializare?</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nume)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

Regele Marius/Views/Specializares/Details.cshtml
@model Regele_Marius.Models.Specializare

@{
    ViewBag.Title = "Details";

    if (Session["NumeUtilizator"] == null || (bool)Session["Activ"] == true)
    {
        Response.Redirect("~/Cont/Logare", false);
    }
}

<h2>Details</h2>

<div>
    <h4>Specializare</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nume)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Regele Marius/Views/Specializares/Edit.cshtml
@model Regele_Marius.Models.Specializare

@{
    ViewBag.Title = "Editare";

    if (Session["NumeUtilizator"] == null || (bool)Session["Activ"] == true)
    {
        Response.Redirect("~/Cont/Logare", false);
    }
}

<h2>Editare specializare</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nume, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nume, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nume, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvare" class="btn btn-success" />
            </div>
        </div>
    </div>
}

Regele Marius/Views/Specializares/Index.cshtml
@model IEnumerable<Regele_Marius.Models.Specializare>
<link href="~/Content/StyleSheet.css" type="text/css" rel="stylesheet" />

@{
    ViewBag.Title = "Specializari";

    if (Session["NumeUtilizator"] == null || (bool)Session["Activ"] == true)
    {
        Response.Redirect("~/Cont/Logare", false);
    }
}

<h1 style="text-align:center">Specializari</h1>

<div class="tooltip">
    @Html.ActionLink(" ", "Create", "Specializares", new { style = "background: url('" + Url.Content("~/images/plus-solid.svg") + "') no-repeat center right; display:inline-block; height:30px; width:30px; filter: invert(11%) sepia(91%) saturate(5572%) hue-rotate(358deg) brightness(88%) contrast(112%);" })
    <span class="tooltiptext">Adauga specializare</span>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nume)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nume)
        </td>
        <td>
            <div class="tooltip">
                @Html.ActionLink(" ", "Delete", "Specializares", new { id = item.Id }, new { style = "background: url('" + Url.Content("~/images/trash.svg") + "') no-repeat center right; display:inline-block; height:30px; width:30px; filter: invert(91%) sepia(0%) saturate(6644%) hue-rotate(138deg) brightness(88%) contrast(84%);" })
                <span class="tooltiptext">Stergere</span>
            </div>
            <div class="tooltip">
                @Html.ActionLink(" ", "Edit", "Specializares", new { id = item.Id }, new { style = "background: url('" + Url.Content("~/images/edit-solid.svg") + "')  no-repeat center; display:inline-block; height:30px; width:30px; filter: invert(11%) sepia(91%) saturate(5572%) hue-rotate(358deg) brightness(88%) contrast(112%);" })
                <span class="tooltiptext">Editare</span>
            </div>
        </td>
    </tr>
}

</table>