Regele Marius/Models/Interventie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Regele_Marius.Models
{
    public class Interventie : Serviciu
    {
        [Required]
        public string Echipament { get; set; }

        public virtual ICollection<ProgramareInterventie> ProgramariInterventie { get; set; }
        public virtual ICollection<RezultatInterventie> RezultateInterventie { get; set; }
    }
}

Regele Marius/Controllers/InterventieController.cs
using Regele_Marius.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Regele_Marius.Controllers
{
    public class InterventieController : Controller
    {
        private ContextClinica _context;

        public InterventieController()
        {
            _context = new ContextClinica();
        }

        // GET: Interventie
        public ActionResult Index()
        {
            var interventii = _context.Interventii.ToList();
            return View(interventii);
        }

        public ActionResult Create()
        {
            return View(new Interventie { Id = 0 });
        }

        [HttpPost]
        public ActionResult Create(Interventie _interventie)
        {
            if (!ModelState.IsValid)
                return View("Create", _interventie);

            if (_interventie.Id > 0)
                _context.Entry(_interventie).State = System.Data.Entity.EntityState.Modified;
            else
                _context.Interventii.Add(_interventie);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var interventie = _context.Interventii.SingleOrDefault(c => c.Id == id);

            if (interventie == null)
                return HttpNotFound();
            _context.Interventii.Remove(interventie);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var interventie = _context.Interventii.SingleOrDefault(c => c.Id == id);
            if (interventie == null)
                return HttpNotFound();

            return View("Create", interventie);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _context.Dispose();
            base.Dispose(disposing);
        }
    }
}

Regele Marius/Views/Interventie/Create.cshtml
@model Regele_Marius.Models.Interventie

@{
    ViewBag.Title = "Interventie noua";

    if (Session["NumeUtilizator"] == null || (bool)Session["Activ"] == false)
    {
        Response.Redirect("~/Cont/Logare", false);
    }
}

<h2>Interventie noua</h2>


@using (Html.BeginForm("Create","Interventie")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Echipament, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Echipament, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Echipament, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Denumire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Denumire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Denumire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descriere, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descriere, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descriere, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pret, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pret, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pret, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.HiddenFor(m => m.Id)
                <input type="submit" value="Salvare" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Inapoi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Regele Marius/Views/Interventie/Index.cshtml
@model IEnumerable<Regele_Marius.Models.Interventie>

@{
    ViewBag.Title = "Lista interventii";

    if (Session["NumeUtilizator"] == null || (bool)Session["Activ"] == false)
    {
        Response.Redirect("~/Cont/Logare", false);
    }
}

<h2>Lista interventii</h2>

<p>
    @Html.ActionLink("Interventie noua", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Echipament)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Denumire)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descriere)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pret)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Echipament)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Denumire)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descriere)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pret)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>